In [119]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
from datascience.predicates import are

In [120]:
Array1 = make_array(['Eric','Hembling','Texas','Blue'])
Array1

array([['Eric', 'Hembling', 'Texas', 'Blue']], dtype='<U8')

In [121]:
Array2 = np.char.upper(Array1)
Array2

array([['ERIC', 'HEMBLING', 'TEXAS', 'BLUE']], dtype='<U8')

In [122]:
Array3 = np.char.count(Array1,'a')
Array3

array([[0, 0, 1, 0]])

In [123]:
[len(i) for i in Array1[0]]

[4, 8, 5, 4]

In [130]:
Array4 = np.arange(1,45,4)
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
Array4 = Array4.astype('float')
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html?highlight=astype#numpy.ndarray.astype
Array4

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

In [131]:
Sum = np.cumsum(Array4)
Sum

array([  1.,   6.,  15.,  28.,  45.,  66.,  91., 120., 153., 190., 231.])

In [132]:
Prod = np.cumprod(Array4)
Prod

array([1.00000000e+00, 5.00000000e+00, 4.50000000e+01, 5.85000000e+02,
       9.94500000e+03, 2.08845000e+05, 5.22112500e+06, 1.51412625e+08,
       4.99661662e+09, 1.84874815e+11, 7.57986742e+12])

In [133]:
Log = np.log(Array4)
Log

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

In [134]:
SumOfDiff = np.sum(np.diff(Array4))
SumOfDiff

40.0